// <auto-generated />
using System;
using GamblersGrocery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamblersGrocery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415112500_Name_Validation_Changed_again1")]
    partial class Name_Validation_Changed_again1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamblersGrocery.Data.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlainPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("price")
                        .IsRequired()
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("stockQuantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Promotion", b =>
                {
                    b.Property<int>("promotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("promotionId"));

                    b.Property<decimal?>("discountPercent")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("promotionId");

                    b.HasIndex("productId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Settlement", b =>
                {
                    b.Property<int>("settlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("settlementId"));

                    b.Property<decimal>("cashInHand")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("cashierId")
                        .HasColumnType("int");

                    b.Property<string>("cashierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("settlementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("totalSales")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("variance")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("settlementId");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.StockLog", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logId"));

                    b.Property<string>("changeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantityChanged")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("logId");

                    b.HasIndex("productId");

                    b.ToTable("StockLogs");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactionId"));

                    b.Property<int>("cashierId")
                        .HasColumnType("int");

                    b.Property<string>("cashierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("discountAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("finalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("paymentMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("transactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("upiId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.TransactionItem", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("itemId"));

                    b.Property<decimal>("lineTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("productDiscount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("transactionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("unitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("itemId");

                    b.HasIndex("productId");

                    b.HasIndex("transactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Promotion", b =>
                {
                    b.HasOne("GamblersGrocery.Models.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.StockLog", b =>
                {
                    b.HasOne("GamblersGrocery.Models.Entities.Product", "Product")
                        .WithMany("StockLogs")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.TransactionItem", b =>
                {
                    b.HasOne("GamblersGrocery.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblersGrocery.Models.Entities.Transaction", "Transaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("transactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Product", b =>
                {
                    b.Navigation("Promotions");

                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("GamblersGrocery.Models.Entities.Transaction", b =>
                {
                    b.Navigation("TransactionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
